import Breadcrumb from "@/components/Common/Breadcrumb";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | StorySizer",
  description:
    "Read StorySizer's Privacy Policy to understand what data we collect, how we process it, and your privacy rights.",
  alternates: {
    canonical: "/privacy-policy",
  },
  openGraph: {
    title: "Privacy Policy | StorySizer",
    description:
      "Learn how StorySizer handles personal data and protects user privacy.",
    url: "/privacy-policy",
    siteName: "StorySizer",
    type: "article",
  },
};

const PrivacyPolicyPage = () => {
  return (
    <>
      <Breadcrumb
        pageName="Privacy Policy"
        description="How StorySizer collects, uses, and protects personal data."
      />

      <section className="pb-16 pt-8 md:pb-20 lg:pb-28">
        <div className="container">
          <div className="mx-auto max-w-[900px] rounded-sm border border-body-color/10 bg-white p-8 dark:border-white/10 dark:bg-dark sm:p-10">
            <p className="mb-6 text-base leading-relaxed text-body-color">
              <strong>Effective date:</strong> 19 April 2026
            </p>

            <h2 className="mb-3 text-xl font-bold text-black dark:text-white">1. Introduction</h2>
            <p className="mb-6 text-base leading-relaxed text-body-color">
              This Privacy Policy explains how StorySizer ("StorySizer", "we", "us", or "our")
              collects, uses, stores, and protects personal data when you use the StorySizer web
              application (the "Service"). StorySizer is a tool designed to support the estimation
              of user stories in story points through a guided questionnaire intended to help users
              rely on more objective parameters rather than rough intuition.
            </p>

            <h2 className="mb-3 text-xl font-bold text-black dark:text-white">2. Data Controller</h2>
            <p className="mb-6 text-base leading-relaxed text-body-color">
              Francesco Maria Falini
              <br />
              Email: francescomaria.falini@gmail.com
            </p>

            <h2 className="mb-3 text-xl font-bold text-black dark:text-white">3. Personal Data We Collect</h2>
            <div className="mb-6 space-y-4 text-base leading-relaxed text-body-color">
              <p>
                <strong>a. Account and authentication data:</strong> your email address and basic
                account data provided through Google Single Sign-On.
              </p>
              <p>
                <strong>b. User-generated content:</strong> user stories submitted to the Service,
                answers provided in the estimation questionnaire, and story point estimates
                generated, saved, or associated with your account.
              </p>
              <p>
                <strong>c. Support and crash-report information:</strong> information you voluntarily
                submit through the crash-report or contact form and any additional details you
                include in your message.
              </p>
              <p>
                <strong>d. Technical and operational data:</strong> basic technical logs that may be
                generated by the website or hosting environment for security, maintenance, and
                troubleshooting purposes.
              </p>
            </div>

            <h2 className="mb-3 text-xl font-bold text-black dark:text-white">4. How We Collect Data</h2>
            <ul className="mb-6 list-disc space-y-2 pl-6 text-base leading-relaxed text-body-color">
              <li>Directly from you, when you log in with Google SSO.</li>
              <li>
                When you use the Service and submit stories, questionnaire responses, and
                estimates.
              </li>
              <li>When you contact us through the crash-report or support form.</li>
            </ul>

            <h2 className="mb-3 text-xl font-bold text-black dark:text-white">5. Purposes of Processing</h2>
            <ul className="mb-6 list-disc space-y-2 pl-6 text-base leading-relaxed text-body-color">
              <li>Provide access to the Service.</li>
              <li>Authenticate users through Google SSO.</li>
              <li>Store and display your user stories, questionnaire answers, and estimates.</li>
              <li>Maintain user-specific memory and estimation history.</li>
              <li>Operate, maintain, debug, and improve the Service.</li>
              <li>Respond to support requests, bug reports, or crash reports.</li>
              <li>Comply with legal obligations, where applicable.</li>
              <li>Protect the security and integrity of the Service.</li>
            </ul>

            <h2 className="mb-3 text-xl font-bold text-black dark:text-white">6. Legal Bases for Processing</h2>
            <ul className="mb-6 list-disc space-y-2 pl-6 text-base leading-relaxed text-body-color">
              <li>
                <strong>Performance of a contract:</strong> to provide the Service you request and
                enable its core functionality.
              </li>
              <li>
                <strong>Legitimate interests:</strong> to maintain security, prevent abuse, debug
                issues, and improve the Service.
              </li>
              <li>
                <strong>Legal obligation:</strong> where processing is necessary to comply with
                applicable law.
              </li>
              <li>
                <strong>Consent:</strong> where consent is specifically required by law for a
                particular processing activity.
              </li>
            </ul>

            <h2 className="mb-3 text-xl font-bold text-black dark:text-white">7. Data Storage and Infrastructure</h2>
            <p className="mb-6 text-base leading-relaxed text-body-color">
              At the moment, the Service is hosted on bare metal infrastructure. In the future, if
              the Service grows, infrastructure may be migrated to a cloud provider. If that
              happens, this Privacy Policy may be updated accordingly to reflect the categories of
              service providers involved.
            </p>

            <h2 className="mb-3 text-xl font-bold text-black dark:text-white">8. Data Sharing</h2>
            <p className="mb-3 text-base leading-relaxed text-body-color">We do not sell your personal data.</p>
            <ul className="mb-6 list-disc space-y-2 pl-6 text-base leading-relaxed text-body-color">
              <li>Authentication providers, such as Google, to enable login.</li>
              <li>Technical service providers involved in hosting, maintenance, or infrastructure.</li>
              <li>
                Legal or public authorities, when required by law or to protect our rights.
              </li>
            </ul>

            <h2 className="mb-3 text-xl font-bold text-black dark:text-white">9. International Transfers</h2>
            <p className="mb-6 text-base leading-relaxed text-body-color">
              If personal data is transferred outside the European Economic Area in the future, we
              will take appropriate steps required by applicable data protection law, including the
              use of lawful transfer mechanisms where necessary.
            </p>

            <h2 className="mb-3 text-xl font-bold text-black dark:text-white">10. Data Retention</h2>
            <p className="mb-3 text-base leading-relaxed text-body-color">
              We retain personal data for as long as reasonably necessary to provide the Service,
              maintain your account and saved estimations, respond to support issues, comply with
              legal obligations, resolve disputes, and enforce our rights.
            </p>
            <p className="mb-6 text-base leading-relaxed text-body-color">
              You may request deletion of your account data by contacting
              francescomaria.falini@gmail.com. We will review and process such requests in
              accordance with applicable law.
            </p>

            <h2 className="mb-3 text-xl font-bold text-black dark:text-white">11. Your Rights</h2>
            <p className="mb-3 text-base leading-relaxed text-body-color">
              Depending on applicable law, including the GDPR, you may have the right to:
            </p>
            <ul className="mb-3 list-disc space-y-2 pl-6 text-base leading-relaxed text-body-color">
              <li>Access your personal data.</li>
              <li>Request rectification of inaccurate data.</li>
              <li>Request deletion of your data.</li>
              <li>Request restriction of processing.</li>
              <li>Object to certain processing.</li>
              <li>Request data portability, where applicable.</li>
              <li>Lodge a complaint with a competent supervisory authority.</li>
            </ul>
            <p className="mb-6 text-base leading-relaxed text-body-color">
              To exercise your rights, contact: francescomaria.falini@gmail.com.
            </p>

            <h2 className="mb-3 text-xl font-bold text-black dark:text-white">12. Security</h2>
            <p className="mb-6 text-base leading-relaxed text-body-color">
              We take reasonable technical and organizational measures to protect personal data
              against unauthorized access, loss, misuse, or alteration. However, no method of
              transmission or storage is completely secure, and we cannot guarantee absolute
              security.
            </p>

            <h2 className="mb-3 text-xl font-bold text-black dark:text-white">13. Business and Confidential Content Disclaimer</h2>
            <p className="mb-6 text-base leading-relaxed text-body-color">
              StorySizer may be used to enter content related to software development activities,
              including user stories and estimation parameters. Users are solely responsible for the
              content they choose to submit to the Service. You should not submit confidential,
              sensitive, classified, or proprietary business information unless you are fully
              authorized to do so and are satisfied that such use is appropriate for your
              organization. StorySizer is provided as a general-purpose estimation tool, and we make
              no representation that the Service is suitable for storing confidential company
              information.
            </p>

            <h2 className="mb-3 text-xl font-bold text-black dark:text-white">14. Children</h2>
            <p className="mb-6 text-base leading-relaxed text-body-color">
              The Service is not specifically directed to children. If you believe that personal data
              of a child has been submitted to the Service without appropriate authorization, please
              contact us and we will review the request and, where appropriate, delete the relevant
              data.
            </p>

            <h2 className="mb-3 text-xl font-bold text-black dark:text-white">15. Open Source and Free Service</h2>
            <p className="mb-6 text-base leading-relaxed text-body-color">
              StorySizer is currently offered free of charge and is intended to be open source. This
              does not affect your privacy rights, but it does mean the Service may evolve over
              time, and this Privacy Policy may be updated as features change.
            </p>

            <h2 className="mb-3 text-xl font-bold text-black dark:text-white">16. Changes to This Privacy Policy</h2>
            <p className="mb-6 text-base leading-relaxed text-body-color">
              We may update this Privacy Policy from time to time. When we do, we will post the
              updated version on the website and update the effective date above. Continued use of
              the Service after changes become effective means you acknowledge the updated Privacy
              Policy.
            </p>

            <h2 className="mb-3 text-xl font-bold text-black dark:text-white">17. Contact</h2>
            <p className="text-base leading-relaxed text-body-color">
              Francesco Maria Falini
              <br />
              francescomaria.falini@gmail.com
            </p>
          </div>
        </div>
      </section>
    </>
  );
};

export default PrivacyPolicyPage;
